### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by QQ2017** [asters1/tts#2]
获取uuid...
创建websocket连接...
websocket连接失败
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x2c9954]

goroutine 1 [running]:
github.com/gorilla/websocket.(*Conn).Close(0xc000107960?)
        D:/OneDrive/MyGopath/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:345 +0x14
panic({0x2f7000, 0x4eb4f0})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x212
github.com/gorilla/websocket.(*Conn).WriteMessage(0x33d836?, 0xc0001d6000?, {0xc0001d61a0, 0x185, 0x1a0})
        D:/OneDrive/MyGopath/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:760 +0x30
main.main()
        C:/Users/admin/Desktop/tts-master/main.go:52 +0x30e

**Comment by QQ2017** [comment]
conn.WriteMessage(websocket.TextMessage, []byte(m1))

出错在这行
